# Enables the serial/UART driver subsystem in Zephyr - UART doesn't work without
CONFIG_SERIAL=y

# Uses interrupt-driven UART instead of polling - uart_cb firiing mechanism when GPS data arrives, instead of constant poll
# *May show linter warning, but the dependencies mentioned are auto-enabled by the nrf52832 (SERIAL_SUPPORT_INTERRUPT)
CONFIG_UART_INTERRUPT_DRIVEN=y

# RTT output instead of COM port - can be removed if we switch
# to a different debug method like a second UART 
# but on nRF52832 with only one UART available this works 
CONFIG_USE_SEGGER_RTT=y

# Routes printk() output to the RTT terminal
CONFIG_RTT_CONSOLE=y

# Disables routing printk() to uart0
# Turning this off frees uart0 exclusively for GPS data
CONFIG_UART_CONSOLE=n

# Switch between raw NMEA output and parsed GPS output.
# Set to y for parsed output, n for raw NMEA strings.
CONFIG_GPS_PARSED_OUTPUT=n

# Only needed when CONFIG_GPS_PARSED_OUTPUT=y
# CONFIG_FPU=y
# CONFIG_CBPRINTF_FP_SUPPORT=y