M48
; DRILL file {KiCad 9.0.7} date 2026-03-20T00:40:06-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-20T00:40:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X51.2Y-12.375
X51.2Y-15.125
T2
X16.67Y-16.14
X16.93Y-76.93
X64.25Y-77.0
X127.25Y-16.25
M30
